
//Status Api

//Service user
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const GETALLUSER_REQUEST_SUCCESS = 'GETALLUSER_REQUEST_SUCCESS';
export const GETALLUSER_SUCCESS = 'GETALLUSER_SUCCESS';
export const GETALLUSER_ERROR = 'GETALLUSER_ERROR';

export const GETUSER_PAGING_REQUEST_SUCCESS = 'GETUSER_PAGING_REQUEST_SUCCESS';
export const GETUSER_PAGING_SUCCESS = 'GETUSER_PAGING_SUCCESS';
export const GETUSER_PAGING_ERROR = 'GETUSER_PAGING_ERROR';

export const CREATE_USER_REQUEST_SUCCESS = 'CREATE_USER_REQUEST_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const UPDATE_USER_REQUEST_SUCCESS = 'UPDATE_USER_REQUEST_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const DELETE_USER_REQUEST_SUCCESS = 'DELETE_USER_REQUEST_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

//Service resource
export const GETALL_RESOURCES_REQUEST_SUCCESS = 'GETALL_RESOURCES_REQUEST_SUCCESS';
export const GETALL_RESOURCES_SUCCESS = 'GETALL_RESOURCES_SUCCESS';
export const GETALL_RESOURCES_ERROR = 'GETALL_RESOURCES_ERROR';

export const GETRESOURCES_PAGING_REQUEST_SUCCESS = 'GETRESOURCES_PAGING_REQUEST_SUCCESS';
export const GETRESOURCES_PAGING_SUCCESS = 'GETRESOURCES_PAGING_SUCCESS';
export const GETRESOURCES_PAGING_ERROR = 'GETRESOURCES_PAGING_ERROR';

export const CREATE_RESOURCES_REQUEST_SUCCESS = 'CREATE_RESOURCES_REQUEST_SUCCESS';
export const CREATE_RESOURCES_SUCCESS = 'CREATE_RESOURCES_SUCCESS';
export const CREATE_RESOURCES_ERROR = 'CREATE_RESOURCES_ERROR';

export const UPDATE_RESOURCES_REQUEST_SUCCESS = 'UPDATE_RESOURCES_REQUEST_SUCCESS';
export const UPDATE_RESOURCES_SUCCESS = 'UPDATE_RESOURCES_SUCCESS';
export const UPDATE_RESOURCES_ERROR = 'UPDATE_RESOURCES_ERROR';

export const DELETE_RESOURCES_REQUEST_SUCCESS = 'DELETE_RESOURCES_REQUEST_SUCCESS';
export const DELETE_RESOURCES_SUCCESS = 'DELETE_RESOURCES_SUCCESS';
export const DELETE_RESOURCES_ERROR = 'DELETE_RESOURCES_ERROR';

//Event app
