export const UNAUTHORIZED = 'UNAUTHORIZED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const GETALLUSER_REQUEST_SUCCESS = 'GETALLUSER_REQUEST_SUCCESS';
export const GETALLUSER_SUCCESS = 'GETALLUSER_SUCCESS';
export const GETALLUSER_ERROR = 'GETALLUSER_ERROR';

export const GETUSER_PAGING_REQUEST_SUCCESS = 'GETUSER_PAGING_REQUEST_SUCCESS';
export const GETUSER_PAGING_SUCCESS = 'GETUSER_PAGING_SUCCESS';
export const GETUSER_PAGING_ERROR = 'GETUSER_PAGING_ERROR';