
//Status Api

//Service user
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const GETALLUSER_REQUEST_SUCCESS = 'GETALLUSER_REQUEST_SUCCESS';
export const GETALLUSER_SUCCESS = 'GETALLUSER_SUCCESS';
export const GETALLUSER_ERROR = 'GETALLUSER_ERROR';

export const GETUSER_PAGING_REQUEST_SUCCESS = 'GETUSER_PAGING_REQUEST_SUCCESS';
export const GETUSER_PAGING_SUCCESS = 'GETUSER_PAGING_SUCCESS';
export const GETUSER_PAGING_ERROR = 'GETUSER_PAGING_ERROR';

export const CREATE_USER_REQUEST_SUCCESS = 'CREATE_USER_REQUEST_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const UPDATE_USER_REQUEST_SUCCESS = 'UPDATE_USER_REQUEST_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const DELETE_USER_REQUEST_SUCCESS = 'DELETE_USER_REQUEST_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

//Event app
