
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';

export const PAGING_SUCCESS = 'PAGING_SUCCESS';
export const PAGING_ERROR = 'PAGING_ERROR';

export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_ERROR = 'CREATE_ERROR';

export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_ERROR = 'UPDATE_ERROR';

export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_ERROR = 'DELETE_ERROR';

export const GET_SELETED_SUCCESS = 'GET_SELETED_SUCCESS';
export const GET_SELETED_ERROR = 'GET_SELETED_ERROR';

export const GET_NEW_MERCHANDISE_CODE_SUCCESS = 'GET_NEW_MERCHANDISE_CODE_SUCCESS';
export const GET_NEW_MERCHANDISE_CODE_ERROR = 'GET_NEW_MERCHANDISE_CODE_ERROR';

export const FIND_BY_ID_SUCCESS = 'FIND_BY_ID_SUCCESS';
export const FIND_BY_ID_ERROR = 'FIND_BY_ID_ERROR';

export const FIND_BY_CODE_SUCCESS = 'FIND_BY_CODE_SUCCESS';
export const FIND_BY_CODE_ERROR = 'FIND_BY_CODE_ERROR';

export const APPROVE_SUCCESS = 'APPROVE_SUCCESS';
export const APPROVE_ERROR = 'APPROVE_ERROR';

export const FIND_BY_MERCHANDISE_ID_SUCCESS = 'FIND_BY_MERCHANDISE_ID_SUCCESS';
export const FIND_BY_MERCHANDISE_ID_ERROR = 'FIND_BY_MERCHANDISE_ID_ERROR';

export const GET_NEW_INSTANCE_SUCCESS = 'GET_NEW_INSTANCE_SUCCESS';
export const GET_NEW_INSTANCE_ERROR = 'GET_NEW_INSTANCE_ERROR';

export const CREATE_UPDATE_SUCCESS = 'CREATE_UPDATE_SUCCESS';
export const CREATE_UPDATE_ERROR = 'CREATE_UPDATE_ERROR';