
//Status Api

//State user
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const GETALLUSER_REQUEST_SUCCESS = 'GETALLUSER_REQUEST_SUCCESS';
export const GETALLUSER_SUCCESS = 'GETALLUSER_SUCCESS';
export const GETALLUSER_ERROR = 'GETALLUSER_ERROR';

export const GETUSER_PAGING_REQUEST_SUCCESS = 'GETUSER_PAGING_REQUEST_SUCCESS';
export const GETUSER_PAGING_SUCCESS = 'GETUSER_PAGING_SUCCESS';
export const GETUSER_PAGING_ERROR = 'GETUSER_PAGING_ERROR';

export const CREATE_USER_REQUEST_SUCCESS = 'CREATE_USER_REQUEST_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const UPDATE_USER_REQUEST_SUCCESS = 'UPDATE_USER_REQUEST_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const DELETE_USER_REQUEST_SUCCESS = 'DELETE_USER_REQUEST_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

//State resource
export const GETALL_RESOURCES_REQUEST_SUCCESS = 'GETALL_RESOURCES_REQUEST_SUCCESS';
export const GETALL_RESOURCES_SUCCESS = 'GETALL_RESOURCES_SUCCESS';
export const GETALL_RESOURCES_ERROR = 'GETALL_RESOURCES_ERROR';

export const GETRESOURCES_PAGING_REQUEST_SUCCESS = 'GETRESOURCES_PAGING_REQUEST_SUCCESS';
export const GETRESOURCES_PAGING_SUCCESS = 'GETRESOURCES_PAGING_SUCCESS';
export const GETRESOURCES_PAGING_ERROR = 'GETRESOURCES_PAGING_ERROR';

export const CREATE_RESOURCES_REQUEST_SUCCESS = 'CREATE_RESOURCES_REQUEST_SUCCESS';
export const CREATE_RESOURCES_SUCCESS = 'CREATE_RESOURCES_SUCCESS';
export const CREATE_RESOURCES_ERROR = 'CREATE_RESOURCES_ERROR';

export const UPDATE_RESOURCES_REQUEST_SUCCESS = 'UPDATE_RESOURCES_REQUEST_SUCCESS';
export const UPDATE_RESOURCES_SUCCESS = 'UPDATE_RESOURCES_SUCCESS';
export const UPDATE_RESOURCES_ERROR = 'UPDATE_RESOURCES_ERROR';

export const DELETE_RESOURCES_REQUEST_SUCCESS = 'DELETE_RESOURCES_REQUEST_SUCCESS';
export const DELETE_RESOURCES_SUCCESS = 'DELETE_RESOURCES_SUCCESS';
export const DELETE_RESOURCES_ERROR = 'DELETE_RESOURCES_ERROR';

export const GET_SELETED_RESOURCES_REQUEST_SUCCESS = 'GET_SELETED_RESOURCES_REQUEST_SUCCESS';
export const GET_SELETED_RESOURCES_SUCCESS = 'GET_SELETED_RESOURCES_SUCCESS';
export const GET_SELETED_RESOURCES_ERROR = 'GET_SELETED_RESOURCES_ERROR';

export const CREATE_RESOURCES_CONTROL_REQUEST_SUCCESS = 'CREATE_RESOURCES_CONTROL_REQUEST_SUCCESS';
export const CREATE_RESOURCES_CONTROL_SUCCESS = 'CREATE_RESOURCES_CONTROL_SUCCESS';
export const CREATE_RESOURCES_CONTROL_ERROR = 'CREATE_RESOURCES_CONTROL_ERROR';

//State role
export const GETALL_ROLE_REQUEST_SUCCESS = 'GETALL_ROLE_REQUEST_SUCCESS';
export const GETALL_ROLE_SUCCESS = 'GETALL_ROLE_SUCCESS';
export const GETALL_ROLE_ERROR = 'GETALL_ROLE_ERROR';

export const GET_SELETED_ROLE_REQUEST_SUCCESS = 'GET_SELETED_ROLE_REQUEST_SUCCESS';
export const GET_SELETED_ROLE_SUCCESS = 'GET_SELETED_ROLE_SUCCESS';
export const GET_SELETED_ROLE_ERROR = 'GET_SELETED_ROLE_ERROR';

export const GETROLE_PAGING_REQUEST_SUCCESS = 'GETROLE_PAGING_REQUEST_SUCCESS';
export const GETROLE_PAGING_SUCCESS = 'GETROLE_PAGING_SUCCESS';
export const GETROLE_PAGING_ERROR = 'GETROLE_PAGING_ERROR';

export const CREATE_ROLE_REQUEST_SUCCESS = 'CREATE_ROLE_REQUEST_SUCCESS';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_ERROR = 'CREATE_ROLE_ERROR';

export const UPDATE_ROLE_REQUEST_SUCCESS = 'UPDATE_ROLE_REQUEST_SUCCESS';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_ERROR = 'UPDATE_ROLE_ERROR';

export const DELETE_ROLE_REQUEST_SUCCESS = 'DELETE_ROLE_REQUEST_SUCCESS';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_ERROR = 'DELETE_ROLE_ERROR';

export const CREATE_USER_ROLE_REQUEST_SUCCESS = 'CREATE_USER_ROLE_REQUEST_SUCCESS';
export const CREATE_USER_ROLE_SUCCESS = 'CREATE_USER_ROLE_SUCCESS';
export const CREATE_USER_ROLE_ERROR = 'CREATE_USER_ROLE_ERROR';

export const GET_USER_ROLE_REQUEST_SUCCESS = 'GET_USER_ROLE_REQUEST_SUCCESS';
export const GET_USER_ROLE_SUCCESS = 'GET_USER_ROLE_SUCCESS';
export const GET_USER_ROLE_ERROR = 'GET_USER_ROLE_ERROR';

export const CREATE_ROLE_PERMISSION_REQUEST_SUCCESS = 'CREATE_ROLE_PERMISSION_REQUEST_SUCCESS';
export const CREATE_ROLE_PERMISSION_SUCCESS = 'CREATE_ROLE_PERMISSION_SUCCESS';
export const CREATE_ROLE_PERMISSION_ERROR = 'CREATE_ROLE_PERMISSION_ERROR';

export const GET_ROLE_PERMISSION_REQUEST_SUCCESS = 'GET_ROLE_PERMISSION_REQUEST_SUCCESS';
export const GET_ROLE_PERMISSION_SUCCESS = 'GET_ROLE_PERMISSION_SUCCESS';
export const GET_ROLE_PERMISSION_ERROR = 'GET_ROLE_PERMISSION_ERROR';

//State Organization
export const GET_ORG_PAGING_REQUEST_SUCCESS = 'GET_ORG_PAGING_REQUEST_SUCCESS';
export const GET_ORG_PAGING_SUCCESS = 'GET_ORG_PAGING_SUCCESS';
export const GET_ORG_PAGING_ERROR = 'GET_ORG_PAGING_ERROR';

export const GETALL_ORGANIZATION_REQUEST_SUCCESS = 'GETALL_ORGANIZATION_REQUEST_SUCCESS';
export const GETALL_ORGANIZATION_SUCCESS = 'GETALL_ORGANIZATION_SUCCESS';
export const GETALL_ORGANIZATION_ERROR = 'GETALL_ORGANIZATION_ERROR';

export const GET_SELETED_ORGANIZATION_REQUEST_SUCCESS = 'GET_SELETED_ORGANIZATION_REQUEST_SUCCESS';
export const GET_SELETED_ORGANIZATION_SUCCESS = 'GET_SELETED_ORGANIZATION_SUCCESS';
export const GET_SELETED_ORGANIZATION_ERROR = 'GET_SELETED_ORGANIZATION_ERROR';

export const GET_CHILD_ORGANIZATION_REQUEST_SUCCESS = 'GET_CHILD_ORGANIZATION_REQUEST_SUCCESS';
export const GET_CHILD_ORGANIZATION_SUCCESS = 'GET_CHILD_ORGANIZATION_SUCCESS';
export const GET_CHILD_ORGANIZATION_ERROR = 'GET_CHILD_ORGANIZATION_ERROR';

export const CREATE_ORGANIZATION_REQUEST_SUCCESS = 'CREATE_ORGANIZATION_REQUEST_SUCCESS';
export const CREATE_ORGANIZATION_SUCCESS = 'CREATE_ORGANIZATION_SUCCESS';
export const CREATE_ORGANIZATION_ERROR = 'CREATE_ORGANIZATION_ERROR';

export const UPDATE_ORGANIZATION_REQUEST_SUCCESS = 'UPDATE_ORGANIZATION_REQUEST_SUCCESS';
export const UPDATE_ORGANIZATION_SUCCESS = 'UPDATE_ORGANIZATION_SUCCESS';
export const UPDATE_ORGANIZATION_ERROR = 'UPDATE_ORGANIZATION_ERROR';

export const DELETE_ORGANIZATION_REQUEST_SUCCESS = 'DELETE_ORGANIZATION_REQUEST_SUCCESS';
export const DELETE_ORGANIZATION_SUCCESS = 'DELETE_ORGANIZATION_SUCCESS';
export const DELETE_ORGANIZATION_ERROR = 'DELETE_ORGANIZATION_ERROR';

export const FIND_ONE_ORG_REQUEST_SUCCESS = 'FIND_ONE_ORG_REQUEST_SUCCESS';
export const FIND_ONE_ORG_SUCCESS = 'FIND_ONE_ORG_SUCCESS';
export const FIND_ONE_ORG_ERROR = 'FIND_ONE_ORG_ERROR';

//State control
export const GETALL_CONTROL_REQUEST_SUCCESS = 'GETALL_CONTROL_REQUEST_SUCCESS';
export const GETALL_CONTROL_SUCCESS = 'GETALL_CONTROL_SUCCESS';
export const GETALL_CONTROL_ERROR = 'GETALL_CONTROL_ERROR';

export const GETCONTROL_PAGING_REQUEST_SUCCESS = 'GETCONTROL_PAGING_REQUEST_SUCCESS';
export const GETCONTROL_PAGING_SUCCESS = 'GETCONTROL_PAGING_SUCCESS';
export const GETCONTROL_PAGING_ERROR = 'GETCONTROL_PAGING_ERROR';

export const CREATE_CONTROL_REQUEST_SUCCESS = 'CREATE_CONTROL_REQUEST_SUCCESS';
export const CREATE_CONTROL_SUCCESS = 'CREATE_CONTROL_SUCCESS';
export const CREATE_CONTROL_ERROR = 'CREATE_CONTROL_ERROR';

export const UPDATE_CONTROL_REQUEST_SUCCESS = 'UPDATE_CONTROL_REQUEST_SUCCESS';
export const UPDATE_CONTROL_SUCCESS = 'UPDATE_CONTROL_SUCCESS';
export const UPDATE_CONTROL_ERROR = 'UPDATE_CONTROL_ERROR';

export const DELETE_CONTROL_REQUEST_SUCCESS = 'DELETE_CONTROL_REQUEST_SUCCESS';
export const DELETE_CONTROL_SUCCESS = 'DELETE_CONTROL_SUCCESS';
export const DELETE_CONTROL_ERROR = 'DELETE_CONTROL_ERROR';
//Event app


//Event real time
export const UPDATE_ROLE = 'UPDATE_ROLE';

//Event real time

