
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';

export const PAGING_SUCCESS = 'PAGING_SUCCESS';
export const PAGING_ERROR = 'PAGING_ERROR';

export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_ERROR = 'CREATE_ERROR';

export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_ERROR = 'UPDATE_ERROR';

export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_ERROR = 'DELETE_ERROR';

export const GET_SELETED_SUCCESS = 'GET_SELETED_SUCCESS';
export const GET_SELETED_ERROR = 'GET_SELETED_ERROR';